<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\Modules\Auth\PetHost.Modules.Auth.Domain\PetHost.Modules.Auth.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Pets\PetHost.Modules.Pets.Domain\PetHost.Modules.Pets.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
  </ItemGroup>

</Project>
