<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- xunit.v3 roda o projeto de teste como executavel. -->
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\Modules\Auth\PetHost.Modules.Auth.Infrastructure\PetHost.Modules.Auth.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\PetHost.TestKit\PetHost.TestKit.csproj" />
  </ItemGroup>

</Project>
