// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PetHost.Modules.Owners.Infrastructure.Persistence;

#nullable disable

namespace PetHost.Modules.Owners.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OwnersDbContext))]
    partial class OwnersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("owner")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PetHost.Modules.Owners.Domain.Owners.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cpf")
                        .HasColumnType("char(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deactivated_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("stripe_customer_id");

                    b.Property<DateTimeOffset?>("SuspendedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("suspended_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_owners");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("uq_owners_cpf");

                    b.HasIndex("StripeCustomerId")
                        .IsUnique()
                        .HasDatabaseName("uq_owners_stripe_customer_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("uq_owners_user_id");

                    b.ToTable("owners", "owner", t =>
                        {
                            t.HasCheckConstraint("ck_owners_cpf_only_null_when_suspended", "cpf IS NOT NULL OR suspended_at IS NOT NULL");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
