// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PetHost.Modules.Audit.Infrastructure.Persistence;

#nullable disable

namespace PetHost.Modules.Audit.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AuditDbContext))]
    partial class AuditDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("audit")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PetHost.Modules.Audit.Domain.Entries.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorRole")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("actor_role");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("target_type");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trace_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_entries");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_audit_entries_occurred_at");

                    b.HasIndex("Action", "OccurredAt")
                        .HasDatabaseName("ix_audit_entries_action");

                    b.HasIndex("ActorId", "OccurredAt")
                        .HasDatabaseName("ix_audit_entries_actor");

                    b.HasIndex("TargetType", "TargetId", "OccurredAt")
                        .HasDatabaseName("ix_audit_entries_target");

                    b.ToTable("audit_entries", "audit");
                });
#pragma warning restore 612, 618
        }
    }
}
