<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PetHost.Modules.Owners.Domain\PetHost.Modules.Owners.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\PetHost.Shared.Kernel\PetHost.Shared.Kernel.csproj" />
    <ProjectReference Include="..\..\..\Shared\PetHost.Shared.Contracts\PetHost.Shared.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
  </ItemGroup>

</Project>
