<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- xunit.v3 roda o projeto de teste como executavel. -->
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\Modules\Hosts\PetHost.Modules.Hosts.Domain\PetHost.Modules.Hosts.Domain.csproj" />
  </ItemGroup>

</Project>
