// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PetHost.Modules.Pets.Infrastructure.Persistence;

#nullable disable

namespace PetHost.Modules.Pets.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PetsDbContext))]
    [Migration("20261009230233_AddUniqueMicrochipToPets")]
    partial class AddUniqueMicrochipToPets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("pet")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PetHost.Modules.Pets.Domain.Pets.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deactivated_at");

                    b.Property<Guid?>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Profile", "PetHost.Modules.Pets.Domain.Pets.Pet.Profile#PetProfile", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Allergies")
                                .HasColumnType("text")
                                .HasColumnName("allergies");

                            b1.Property<DateOnly?>("BirthDate")
                                .HasColumnType("date")
                                .HasColumnName("birth_date");

                            b1.Property<string>("Breed")
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("breed");

                            b1.Property<string>("FeedingNotes")
                                .HasColumnType("text")
                                .HasColumnName("feeding_notes");

                            b1.Property<bool>("GoodWithCats")
                                .HasColumnType("boolean")
                                .HasColumnName("good_with_cats");

                            b1.Property<bool>("GoodWithDogs")
                                .HasColumnType("boolean")
                                .HasColumnName("good_with_dogs");

                            b1.Property<bool>("GoodWithKids")
                                .HasColumnType("boolean")
                                .HasColumnName("good_with_kids");

                            b1.Property<bool>("IsNeutered")
                                .HasColumnType("boolean")
                                .HasColumnName("is_neutered");

                            b1.Property<bool>("IsVaccinated")
                                .HasColumnType("boolean")
                                .HasColumnName("is_vaccinated");

                            b1.Property<string>("MedicationNotes")
                                .HasColumnType("text")
                                .HasColumnName("medication_notes");

                            b1.Property<string>("Microchip")
                                .HasColumnType("char(15)")
                                .HasColumnName("microchip");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("name");

                            b1.Property<string>("Notes")
                                .HasColumnType("text")
                                .HasColumnName("notes");

                            b1.Property<string>("PhotoUrl")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("photo_url");

                            b1.Property<string>("Sex")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("sex");

                            b1.Property<string>("Size")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("size");

                            b1.Property<string>("Species")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("species");

                            b1.Property<string>("SpeciesDescription")
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("species_description");

                            b1.Property<string>("VetContact")
                                .HasMaxLength(160)
                                .HasColumnType("character varying(160)")
                                .HasColumnName("vet_contact");

                            b1.Property<decimal?>("WeightKg")
                                .HasPrecision(6, 3)
                                .HasColumnType("numeric(6,3)")
                                .HasColumnName("weight_kg");
                        });

                    b.HasKey("Id")
                        .HasName("pk_pets");

                    b.HasIndex("HostId")
                        .HasDatabaseName("ix_pets_host_id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_pets_owner_id");

                    b.ToTable("pets", "pet", t =>
                        {
                            t.HasCheckConstraint("ck_pets_description_only_for_exotic", "(species = 'exotic') = (species_description IS NOT NULL)");

                            t.HasCheckConstraint("ck_pets_one_keeper", "num_nonnulls(owner_id, host_id) = 1");

                            t.HasCheckConstraint("ck_pets_sex", "sex IN ('male', 'female', 'unknown')");

                            t.HasCheckConstraint("ck_pets_size", "size IS NULL OR size IN ('small', 'medium', 'large')");

                            t.HasCheckConstraint("ck_pets_size_only_for_dogs_and_cats", "size IS NULL OR species IN ('dog', 'cat')");

                            t.HasCheckConstraint("ck_pets_size_required_for_dogs", "species <> 'dog' OR size IS NOT NULL");

                            t.HasCheckConstraint("ck_pets_species", "species IN ('dog', 'cat', 'cockatiel', 'parrot', 'parakeet', 'canary', 'rabbit', 'hamster', 'guinea_pig', 'fish', 'turtle', 'exotic')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
