// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PetHost.Modules.Hosts.Infrastructure.Persistence;

#nullable disable

namespace PetHost.Modules.Hosts.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HostsDbContext))]
    partial class HostsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("host")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PetHost.Modules.Hosts.Domain.Hosts.Host", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cnpj")
                        .HasColumnType("char(14)")
                        .HasColumnName("cnpj");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("char(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deactivated_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LegalName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("legal_name");

                    b.Property<string>("PersonType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("person_type");

                    b.Property<string>("StripeAccountId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("stripe_account_id");

                    b.Property<DateTimeOffset?>("SuspendedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("suspended_at");

                    b.Property<string>("TradeName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("trade_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CompanyAddress", "PetHost.Modules.Hosts.Domain.Hosts.Host.CompanyAddress#CompanyAddress", b1 =>
                        {
                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("company_city");

                            b1.Property<string>("Complement")
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("company_complement");

                            b1.Property<string>("Neighborhood")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("company_neighborhood");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("company_street_number");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("char(2)")
                                .HasColumnName("company_state");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("company_street");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasColumnType("char(8)")
                                .HasColumnName("company_zip_code");
                        });

                    b.HasKey("Id")
                        .HasName("pk_hosts");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("uq_hosts_cnpj");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("uq_hosts_cpf_individual")
                        .HasFilter("person_type = 'individual'");

                    b.HasIndex("StripeAccountId")
                        .IsUnique()
                        .HasDatabaseName("uq_hosts_stripe_account_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("uq_hosts_user_id");

                    b.ToTable("hosts", "host", t =>
                        {
                            t.HasCheckConstraint("ck_hosts_company_data", "(person_type = 'company' AND cnpj IS NOT NULL AND legal_name IS NOT NULL AND trade_name IS NOT NULL AND company_zip_code IS NOT NULL AND company_street IS NOT NULL AND company_street_number IS NOT NULL AND company_neighborhood IS NOT NULL AND company_city IS NOT NULL AND company_state IS NOT NULL) OR (person_type = 'individual' AND cnpj IS NULL AND legal_name IS NULL AND trade_name IS NULL AND company_zip_code IS NULL AND company_street IS NULL AND company_street_number IS NULL AND company_complement IS NULL AND company_neighborhood IS NULL AND company_city IS NULL AND company_state IS NULL)");

                            t.HasCheckConstraint("ck_hosts_person_type", "person_type IN ('individual', 'company')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
